spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDB_HOST}:${RDB_PORT}/${RDB_SCHEMA}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}

jwt:
  access-token:
    secret: ${JWT_ACCESS_TOKEN_SECRET}
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    secret: ${JWT_REFRESH_TOKEN_SECRET}
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

coolsms:
  key: ${COOLSMS_API_KEY}
  secret: ${COOLSMS_API_SECRET}
  sender: ${COOLSMS_SENDER}
  ttl: ${COOLSMS_TTL}